# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 20:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190927_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='points_chain',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(null=True), default=[], size=None),
        ),
    ]
