# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-28 17:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190927_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='(updates on save)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='points_chain',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=[], size=None),
        ),
    ]
