# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-01 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190928_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='owner_id',
            field=models.PositiveIntegerField(),
        ),
    ]
